version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.10"
  jobs:
    post_checkout:
      - mv moderngl moderngl-package
      - cp moderngl-stubs/__init__.pyi moderngl.py

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py

formats: all
