name: coverage

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:

  coverage:
    name: coverage
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: build
        run: docker build . -f tests/coverage/Dockerfile -t coverage

      - name: coverage
        run: docker run --rm -t coverage
