name: release

on:
  workflow_dispatch:

jobs:

  sdist:
    name: Package source
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: deps
        run: python -m pip install -U pip wheel setuptools

      - name: sdist
        run: python setup.py sdist -d package

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: package/*.tar.gz

  wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-14]

    env:
      CIBW_BUILD: cp38-* cp39-* cp310-* cp312-*

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5

      - name: deps
        run: python -m pip install cibuildwheel==2.19.1

      - name: wheels
        run: python -m cibuildwheel --output-dir package

      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: package/*.whl
