name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: build
        run: docker build . -f tests/Containerfile -t tests

      - name: test
        run: docker run --rm -t tests
